config/routes.rb
Rails.application.routes.draw do
  root 'workouts#home'

  resources :workouts

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  validates :name, :set, :rep, :day, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def new
    @workout = Workout.new
  end

  def show
    @workout = Workout.find(params[:id])
  end

  def index
    @workout = Workout.all
  end

  def create
    @workout = Workout.new(user_params)

    if @workout.save
      redirect_to @workout
    else
      render 'new'
    end
  end


  private

    def user_params
      params.require(:workout).permit(:name, :set, :rep, :weight, :day)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p><%= link_to 'Homepage', root_path %></p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkoutTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @workout.errors.any? %>
  <div id="error_explanation">
    <div class="error">
      Workout not added, the form contains <%= pluralize(@workout.errors.count, "error") %>:
    </div>
    <ul>
    <% @workout.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/workouts/home.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<h1>Welcome to the Workout Tracker!</h1>

<h3>This site helps you keep track of your workouts, so you can refer back to them whenever you need to. Happy tracking...</h3>

<p><%= link_to 'View all workouts', workouts_path %>
<p><%= link_to 'Add a new workout log', new_workout_path %>

app/views/workouts/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<h1>All workouts</h1>

<% @workout.group_by{ |i| i.day }.sort_by{|key, w| key}.reverse.each do |date, daily_workouts| %>

  <h3><%= date %></h3>
  <table>
    <thead>
      <tr align="left">
        <th> Workout Name </th>
        <th>Set</th>
        <th>Rep(s)</th>
        <th>Weight (kg)</th>
      </tr>
    </thead>
    <% daily_workouts.each do |workout| %>
      <tr>
        <td><%= workout.name %></td>
        <td><%= workout.set %></td>
        <td><%= workout.rep %></td>
        <% if workout.weight %>
          <td><%= workout.weight %></td>
        <% else %>
          <td> n/a </td>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

<%= render 'layouts/footer' %>

app/views/workouts/new.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<h1>Add a new workout</h1>
<h2>Enter your workout details below</h2>

<div class="row">
  <%= form_for(@workout) do |f| %>
    <%= render 'shared/error_messages' %>

    <div class="col-2">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'error' %>
    </div>

    <div class="col-2">
      <%= f.label :set %>
      <%= f.text_field :set, class: 'error' %>
    </div>

    <div class="col-2">
      <%= f.label :rep %>
      <%= f.text_field :rep, class: 'error' %>
    </div>

    <div class="col-2">
      <%= f.label :weight %> (optional)
      <%= f.text_field :weight, class: 'error' %>
    </div>

    <div class="col-2">
      <%= f.label :day %>
      <%= f.date_field :day, class: 'error' %>
    </div>

      <%= f.submit "Add workout", class: "sub-button" %>

  <% end %>
</div>

<%= render 'layouts/footer' %>

app/views/workouts/show.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<h1>Workout details on <%= @workout.day %> has been logged</h1>

<h3>Exercise:</h3><%= @workout.name %>
<h3>Set:</h3><%= @workout.set %>
<h3>Rep:</h3><%= @workout.rep %>

<p><%= link_to 'Add another workout log', new_workout_path %>
<p><%= link_to 'Homepage', root_path %>